version: "2"

linters:
  default: standard
  disable:
    # Covered by SonarCloud - code smells
    - gocyclo        # cyclomatic complexity
    - cyclop         # cyclomatic complexity (alternative)
    - funlen         # function length
    - lll            # line length

    # Covered by SonarCloud - unused code
    - unused         # unused variables/constants

    # Covered by SonarCloud - style/comments
    - godot          # comments ending with period

    # Covered by SonarCloud - security
    - gosec          # security issues

    # Covered by SonarCloud - bugs
    - ineffassign    # ineffectual assignments

  settings:
    revive:
      rules:
        # Disable package comment requirement (SonarCloud covers this)
        - name: package-comments
          disabled: true
        # Disable exported comment requirement
        - name: exported
          disabled: true

    staticcheck:
      checks:
        - "all"
        - "-ST1000"  # package comments (SonarCloud covers this)
        - "-ST1003"  # naming conventions
        - "-ST1016"  # receiver naming
        - "-ST1020"  # comment on exported function
        - "-ST1021"  # comment on exported type
        - "-ST1022"  # comment on exported var
        - "-SA4006"  # unused value (SonarCloud covers this)
        - "-QF1001"  # De Morgan's law suggestion (style preference)
