version: "2"

run:
  # your existing run settings
  concurrency: 4
  timeout: 5m

linters:
  # replace disable-all / enable-all
  default: none                     # run *only* the linters you list below :contentReference[oaicite:3]{index=3}
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
  disable: []                       # if there are any you want to turn off

  settings:                         # ← move *all* per-linter settings here (not at top level)
    errcheck:
      check-type-assertions: true
    govet:
      # in v2, check-shadowing was removed; use enable: [shadow] instead
      enable:
        - shadow                    # :contentReference[oaicite:4]{index=4}
    gocyclo:
      min-complexity: 15
    staticcheck:
      checks:
        - "all"