// Test code generated by code-agent (AI agent). DO NOT EDIT MANUALLY.
// Purpose:
// - To increase coverage
//

package tcap

import "testing"

func TestMessageTypes(t *testing.T) {
	end := &EndTCAP{}
	if end.MessageType() != MessageTypeEnd {
		t.Errorf("Expected MessageTypeEnd, got %v", end.MessageType())
	}

	abort := &AbortTCAP{}
	if abort.MessageType() != MessageTypeAbort {
		t.Errorf("Expected MessageTypeAbort, got %v", abort.MessageType())
	}

	cont := &ContinueTCAP{}
	if cont.MessageType() != MessageTypeContinue {
		t.Errorf("Expected MessageTypeContinue, got %v", cont.MessageType())
	}

	beg := &BeginTCAP{}
	if beg.MessageType() != MessageTypeBegin {
		t.Errorf("Expected MessageTypeBegin, got %v", beg.MessageType())
	}
}

func TestNewDialogueResponseFromDialogueRequest(t *testing.T) {
	// Case 1: Nil input
	if res, err := NewDialogueResponseFromDialogueRequest(nil); res != nil || err != nil {
		t.Error("Expected nil, nil for nil input")
	}

	// Case 2: DialogueRequest is nil
	dial := &DialogueTCAP{}
	if _, err := NewDialogueResponseFromDialogueRequest(dial); err == nil {
		t.Error("Expected error for nil DialogueRequest")
	}

	// Case 3: Valid
	dial = newDialogueRequest(1, 1)
	res, err := NewDialogueResponseFromDialogueRequest(dial)
	if err != nil {
		t.Errorf("Failed to create response: %v", err)
	}
	if res == nil || res.DialogueResponse == nil {
		t.Error("Created response is nil or missing DialogueResponse")
	}
}
