// Test code generated by code-agent (AI agent). DO NOT EDIT MANUALLY.
// Purpose:
// - To increase coverage
//

package tcap

import (
	"bytes"
	"testing"
)

func TestUnidirectionalTCAP_Marshal_Parse(t *testing.T) {
	// Create a UnidirectionalTCAP message
	uni := &UnidirectionalTCAP{
		Components: ComponentTCAP{
			Invoke: &InvokeTCAP{
				InvokeID:  1,
				OpCode:    0x02,
				Parameter: []byte{0x02, 0x01, 0x05},
			},
		},
	}

	// Test Marshal
	encoded, err := uni.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal UnidirectionalTCAP: %v", err)
	}

	if len(encoded) == 0 {
		t.Fatal("Encoded UnidirectionalTCAP is empty")
	}

	// Test MessageType
	if uni.MessageType() != MessageTypeUnidirectional {
		t.Errorf("Expected MessageTypeUnidirectional, got %v", uni.MessageType())
	}

	// Test Parse (ParseDER)
	parsed, err := ParseDER(encoded)
	if err != nil {
		t.Fatalf("Failed to parse encoded UnidirectionalTCAP: %v", err)
	}

	// Verify parsed type
	parsedUni, ok := parsed.(*UnidirectionalTCAP)
	if !ok {
		t.Fatalf("Expected *UnidirectionalTCAP, got %T", parsed)
	}

	// Verify content
	if parsedUni.Components.Invoke == nil {
		t.Fatal("Parsed UnidirectionalTCAP missing Invoke component")
	}
	if parsedUni.Components.Invoke.InvokeID != 1 {
		t.Errorf("Expected InvokeID 1, got %d", parsedUni.Components.Invoke.InvokeID)
	}
	if !bytes.Equal(parsedUni.Components.Invoke.Parameter, []byte{0x02, 0x01, 0x05}) {
		t.Errorf("Expected Parameter [2 1 5], got %v", parsedUni.Components.Invoke.Parameter)
	}
}

func TestUnidirectionalTCAP_WithDialogue(t *testing.T) {
	uni := &UnidirectionalTCAP{
		Dialogue: &DialogueTCAP{
			DialogAsId: []int{1, 2, 3},
			DialogueRequest: &AARQapduTCAP{
				ProtocolVersionPadded: uint8Ptr(128),
				AcnVersion:            []int{1, 2},
			},
		},
	}

	enc, err := uni.Marshal()
	if err != nil {
		t.Fatalf("Marshal failed: %v", err)
	}

	parsed, err := ParseDER(enc)
	if err != nil {
		t.Fatalf("Parse failed: %v", err)
	}

	parsedUni, ok := parsed.(*UnidirectionalTCAP)
	if !ok {
		t.Fatalf("Expected *UnidirectionalTCAP, got %T", parsed)
	}

	if parsedUni.Dialogue == nil {
		t.Fatal("Parsed Dialogue is nil")
	}
	if parsedUni.Dialogue.DialogueRequest == nil {
		t.Fatal("Parsed DialogueRequest is nil")
	}
}

func TestRejectComponent_Marshal_Parse(t *testing.T) {
	// Create a UnidirectionalTCAP with Reject component
	problem := uint8(1) // UnrecognizedComponent
	invID := uint8(2)
	uni := &UnidirectionalTCAP{
		Components: ComponentTCAP{
			Reject: &RejectTCAP{
				DerivableOrNotDerivable: &invID,
				GeneralProblem:          &problem,
			},
		},
	}

	encoded, err := uni.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal UnidirectionalTCAP with Reject: %v", err)
	}

	parsed, err := ParseDER(encoded)
	if err != nil {
		t.Fatalf("Failed to parse: %v", err)
	}

	parsedUni, ok := parsed.(*UnidirectionalTCAP)
	if !ok {
		t.Fatalf("Expected *UnidirectionalTCAP, got %T", parsed)
	}

	if parsedUni.Components.Reject == nil {
		t.Fatal("Parsed UnidirectionalTCAP missing Reject component")
	}
	if parsedUni.Components.Reject.GeneralProblem == nil {
		t.Fatal("Parsed Reject component missing GeneralProblem")
	}
	if *parsedUni.Components.Reject.GeneralProblem != 1 {
		t.Errorf("Expected GeneralProblem 1, got %d", *parsedUni.Components.Reject.GeneralProblem)
	}
	if parsedUni.Components.Reject.DerivableOrNotDerivable == nil {
		t.Fatal("Parsed Reject component missing DerivableOrNotDerivable")
	}
	if *parsedUni.Components.Reject.DerivableOrNotDerivable != 2 {
		t.Errorf("Expected DerivableOrNotDerivable 2, got %d", *parsedUni.Components.Reject.DerivableOrNotDerivable)
	}
}

func TestRejectComponent_Variants(t *testing.T) {
	// Problem types
	genProb := uint8(1)
	invProb := uint8(2)
	rrProb := uint8(3)
	reProb := uint8(4)

	variants := []struct {
		name string
		rej  *RejectTCAP
	}{
		{"GeneralProblem", &RejectTCAP{GeneralProblem: &genProb}},
		{"InvokeProblem", &RejectTCAP{InvokeProblem: &invProb}},
		{"ReturnResultProblem", &RejectTCAP{ReturnResultProblem: &rrProb}},
		{"ReturnErrorProblem", &RejectTCAP{ReturnErrorProblem: &reProb}},
		{"DefaultProblem", &RejectTCAP{}}, // Should default to UnrecognizedComponent
	}

	for _, v := range variants {
		t.Run(v.name, func(t *testing.T) {
			uni := &UnidirectionalTCAP{
				Components: ComponentTCAP{
					Reject: v.rej,
				},
			}
			enc, err := uni.Marshal()
			if err != nil {
				t.Fatalf("Marshal failed: %v", err)
			}
			parsed, err := ParseDER(enc)
			if err != nil {
				t.Fatalf("Parse failed: %v", err)
			}
			parsedUni, ok := parsed.(*UnidirectionalTCAP)
			if !ok {
				t.Fatalf("Expected *UnidirectionalTCAP, got %T", parsed)
			}
			if parsedUni.Components.Reject == nil {
				t.Fatal("Parsed Reject is nil")
			}
		})
	}
}
