// Test code generated by code-agent (AI agent). DO NOT EDIT MANUALLY.
// Purpose:
// - To increase coverage
//

package tcap

import "testing"

func TestNewBegin_Options(t *testing.T) {
	otid := []byte{0x01, 0x02}

	// WithBeginDialogueRequest
	beg, err := NewBegin(otid, WithBeginDialogueRequest(1, 1))
	if err != nil {
		t.Errorf("NewBegin failed with DialogueRequest: %v", err)
	}
	tcBeg, ok := beg.(*BeginTCAP)
	if !ok || tcBeg.Dialogue == nil || tcBeg.Dialogue.DialogueRequest == nil {
		t.Error("NewBegin failed to set DialogueRequest")
	}

	// WithBeginDialogueObject
	dial := &DialogueTCAP{DialogAsId: []int{1}}
	beg, err = NewBegin(otid, WithBeginDialogueObject(dial))
	if err != nil {
		t.Errorf("NewBegin failed with DialogueObject: %v", err)
	}
	tcBeg, ok = beg.(*BeginTCAP)
	if !ok || tcBeg.Dialogue != dial {
		t.Error("NewBegin failed to set DialogueObject")
	}
}
