// Test code generated by code-agent (AI agent). DO NOT EDIT MANUALLY.
// Purpose:
// - To increase coverage
//

package tcap

import "testing"

func TestNewEnd_Options(t *testing.T) {
	dtid := []byte{0x01, 0x02, 0x03, 0x04}

	// WithEndDialogueResponse
	end, err := NewEnd(dtid, WithEndDialogueResponse(1, 1))
	if err != nil {
		t.Errorf("NewEnd failed with DialogueResponse: %v", err)
	}
	tcEnd, ok := end.(*EndTCAP)
	if !ok || tcEnd.Dialogue == nil || tcEnd.Dialogue.DialogueResponse == nil {
		t.Error("NewEnd failed to set DialogueResponse")
	}

	// WithEndDialogueObject
	dial := &DialogueTCAP{DialogAsId: []int{1, 2, 3}}
	end, err = NewEnd(dtid, WithEndDialogueObject(dial))
	if err != nil {
		t.Errorf("NewEnd failed with DialogueObject: %v", err)
	}
	tcEnd, ok = end.(*EndTCAP)
	if !ok || tcEnd.Dialogue != dial {
		t.Error("NewEnd failed to set DialogueObject")
	}

	// WithEndReturnResultLast
	opCode := uint8(1)
	end, err = NewEnd(dtid, WithEndReturnResultLast(1, &opCode, []byte{0x01}))
	if err != nil {
		t.Errorf("NewEnd failed with ReturnResultLast: %v", err)
	}
	tcEnd, ok = end.(*EndTCAP)
	if !ok || tcEnd.Components.ReturnResultLast == nil {
		t.Error("NewEnd failed to set ReturnResultLast")
	}

	// WithEndReturnError
	end, err = NewEnd(dtid, WithEndReturnError(1, 2, []byte{0x01}))
	if err != nil {
		t.Errorf("NewEnd failed with ReturnError: %v", err)
	}
	tcEnd, ok = end.(*EndTCAP)
	if !ok || tcEnd.Components.ReturnError == nil {
		t.Error("NewEnd failed to set ReturnError")
	}
}

func TestNewEnd_Errors(t *testing.T) {
	// Invalid DTID
	if _, err := NewEnd([]byte{}); err == nil {
		t.Error("Expected error for empty DTID")
	}

	// Option error
	errOpt := func(e *EndTCAP) error { return &ParseError{Op: "test", Err: nil} }
	if _, err := NewEnd([]byte{0x01}, errOpt); err == nil {
		t.Error("Expected error from option")
	}
}

func TestNewEnd_ComponentOptions_InvalidInvokeID(t *testing.T) {
	dtid := []byte{0x02}

	// WithEndReturnResultLast
	if _, err := NewEnd(dtid, WithEndReturnResultLast(1000, nil, nil)); err == nil {
		t.Error("Expected error for invalid InvokeID in WithEndReturnResultLast")
	}

	// WithEndReturnError
	if _, err := NewEnd(dtid, WithEndReturnError(1000, 1, nil)); err == nil {
		t.Error("Expected error for invalid InvokeID in WithEndReturnError")
	}
}
