// Test code generated by code-agent (AI agent). DO NOT EDIT MANUALLY.
// Purpose:
// - To increase coverage
//

package tcap

import "testing"

func TestNewContinue_Options(t *testing.T) {
	otid := []byte{0x01, 0x02}
	dtid := []byte{0x03, 0x04}

	// WithContinueDialogueRequest
	cont, err := NewContinue(otid, dtid, WithContinueDialogueRequest(1, 1))
	if err != nil {
		t.Errorf("NewContinue failed with DialogueRequest: %v", err)
	}
	tcCont, ok := cont.(*ContinueTCAP)
	if !ok || tcCont.Dialogue == nil || tcCont.Dialogue.DialogueRequest == nil {
		t.Error("NewContinue failed to set DialogueRequest")
	}

	// WithContinueDialogueResponse
	cont, err = NewContinue(otid, dtid, WithContinueDialogueResponse(1, 1))
	if err != nil {
		t.Errorf("NewContinue failed with DialogueResponse: %v", err)
	}
	tcCont, ok = cont.(*ContinueTCAP)
	if !ok || tcCont.Dialogue == nil || tcCont.Dialogue.DialogueResponse == nil {
		t.Error("NewContinue failed to set DialogueResponse")
	}

	// WithContinueDialogueObject
	dial := &DialogueTCAP{DialogAsId: []int{1}}
	cont, err = NewContinue(otid, dtid, WithContinueDialogueObject(dial))
	if err != nil {
		t.Errorf("NewContinue failed with DialogueObject: %v", err)
	}
	tcCont, ok = cont.(*ContinueTCAP)
	if !ok || tcCont.Dialogue != dial {
		t.Error("NewContinue failed to set DialogueObject")
	}

	// WithContinueReturnResultLast
	opCode := uint8(1)
	cont, err = NewContinue(otid, dtid, WithContinueReturnResultLast(1, &opCode, []byte{0x01}))
	if err != nil {
		t.Errorf("NewContinue failed with ReturnResultLast: %v", err)
	}
	tcCont, ok = cont.(*ContinueTCAP)
	if !ok || tcCont.Components.ReturnResultLast == nil {
		t.Error("NewContinue failed to set ReturnResultLast")
	}
}

func TestWithContinueInvoke(t *testing.T) {
	otid := []byte{0x01, 0x02}
	dtid := []byte{0x03, 0x04}
	opCode := uint8(1)

	cont, err := NewContinue(otid, dtid, WithContinueInvoke(1, opCode, []byte{0x01}))
	if err != nil {
		t.Errorf("NewContinue failed with Invoke: %v", err)
	}
	tcCont, ok := cont.(*ContinueTCAP)
	if !ok || tcCont.Components.Invoke == nil {
		t.Error("NewContinue failed to set Invoke")
	}
}

func TestNewContinue_Errors(t *testing.T) {
	// Invalid OTID
	if _, err := NewContinue([]byte{}, []byte{0x01}); err == nil {
		t.Error("Expected error for empty OTID")
	}
	// Invalid DTID
	if _, err := NewContinue([]byte{0x01}, []byte{}); err == nil {
		t.Error("Expected error for empty DTID")
	}

	// Option error
	errOpt := func(c *ContinueTCAP) error { return &ParseError{Op: "test", Err: nil} }
	if _, err := NewContinue([]byte{0x01}, []byte{0x02}, errOpt); err == nil {
		t.Error("Expected error from option")
	}
}

func TestNewContinue_ComponentOptions_InvalidInvokeID(t *testing.T) {
	otid := []byte{0x01}
	dtid := []byte{0x02}

	// WithContinueInvoke
	if _, err := NewContinue(otid, dtid, WithContinueInvoke(1000, 1, nil)); err == nil {
		t.Error("Expected error for invalid InvokeID in WithContinueInvoke")
	}

	// WithContinueReturnResultLast
	if _, err := NewContinue(otid, dtid, WithContinueReturnResultLast(1000, nil, nil)); err == nil {
		t.Error("Expected error for invalid InvokeID in WithContinueReturnResultLast")
	}
}
